=== MarkM-Portfolio/homepage/sn.homepage/lwp/homepage.web.layer/core/config.files/gettingstarted-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- ***************************************************************** -->
<!--                                                                   -->
<!-- IBM Confidential                                                  -->
<!--                                                                   -->
<!-- OCO Source Materials                                              -->
<!--                                                                   -->
<!-- Copyright IBM Corp. 2009, 2015                                    -->
<!--                                                                   -->
<!-- The source code for this program is not published or otherwise    -->
<!-- divested of its trade secrets, irrespective of what has been      -->
<!-- deposited with the U.S. Copyright Office.                         -->
<!--                                                                   -->
<!-- ***************************************************************** -->

<!-- 5724-S68                                                          -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:element name='config'>
		<xs:complexType>
			<xs:choice>
				<xs:element ref='url' minOccurs='1' maxOccurs='1'/>
				<xs:element ref='steps' minOccurs="1" maxOccurs="1"/>				
			</xs:choice>
			<xs:attribute name='id' use='required' type='xs:NMTOKEN' />
			<xs:attribute name='buildlevel' type="xs:string" use='required'/>
			<xs:attribute name='version' use='required' type='xs:NMTOKEN' />
			<xs:attribute name="enabled" type="xs:boolean" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="url">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="target" type="xs:string"></xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="steps">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref='step' minOccurs='1' maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="step">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="title" maxOccurs="1" minOccurs="1" />
				<xs:element ref="body-links" maxOccurs="1" minOccurs="1" />
			</xs:sequence>
			<xs:attribute name="enabled" type="xs:boolean" use="required"/>
		</xs:complexType>
	</xs:element>


	<xs:simpleType name="title_string">
		<xs:restriction base="xs:token">
			<xs:minLength value="1"/>
		</xs:restriction>
	</xs:simpleType>
	

	<xs:element name="title">
		<xs:complexType>
    			<xs:simpleContent>
      				<xs:extension base="title_string">
       					<xs:attribute name="bundle" type="xs:string" use="optional"/>
      				</xs:extension>
    			</xs:simpleContent>
		</xs:complexType>
	</xs:element>


	<xs:element name="body-links">
		<xs:complexType>
			<xs:attribute name="secure" type="xs:string" use="required"/>
			<xs:attribute name="unsecure" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element> 

</xs:schema>

=== MarkM-Portfolio/homepage/sn.homepage/lwp/homepage.web.layer/core/config.files.backup/gettingstarted-config-45.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ***************************************************************** -->
<!--                                                                   -->
<!-- IBM Confidential                                                  -->
<!--                                                                   -->
<!-- OCO Source Materials                                              -->
<!--                                                                   -->
<!-- Copyright IBM Corp. 2008, 2015                                    -->
<!--                                                                   -->
<!-- The source code for this program is not published or otherwise    -->
<!-- divested of its trade secrets, irrespective of what has been      -->
<!-- deposited with the U.S. Copyright Office.                         -->
<!--                                                                   -->
<!-- ***************************************************************** -->

<!-- 5724-S68                                                          -->
<config id="gettingstarted-config" version="3.0" buildlevel="LC3.0_20100316_0017"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="gettingstarted-config.xsd" enabled="true">
    <steps>	
    
    <!-- This step is displayed in a new deployment but should be either disabled or 
         replaced with your own content before you make your deployment available to users. -->
	<step enabled="true">
		<title bundle="com.ibm.lconn.homepage.resources.nls.jsp.jsp_resources">jsp.start.step1.tab.title</title>
		<body-links
			secure="${lcurl:homepage.secure}/web/stepOnePage.action"
			unsecure="${lcurl:homepage.unsecure}/web/stepOnePage.action" />
	</step>

	<step enabled="true">
		<title bundle="com.ibm.lconn.homepage.resources.nls.jsp.jsp_resources">jsp.start.share.tab.title</title>
		<body-links 
			secure="${lcurl:homepage.secure}/web/shareStepPage.action"
			unsecure="${lcurl:homepage.unsecure}/web/shareStepPage.action" />
	</step>
	
	<step enabled="true">
		<title bundle="com.ibm.lconn.homepage.resources.nls.jsp.jsp_resources">jsp.start.explore.tab.title</title>
		<body-links 
			secure="${lcurl:homepage.secure}/web/exploreStepPage.action"
			unsecure="${lcurl:homepage.unsecure}/web/exploreStepPage.action" />
	</step>
    </steps>	
</config>
